### Get all users
GET http://localhost:8080/api/users

### Create a new user
POST http://localhost:8080/api/users/create
Content-Type: application/json

{
  "username": "milla"
}

### Get a user by UUID
GET http://localhost:8080/api/users/baf9e149-9937-47b1-8b8a-b7832842d181

### Get all activities
GET http://localhost:8080/api/activities

### Create a new activity
POST http://localhost:8080/api/activities/create
Content-Type: application/json

{
  "userUUID": "baf9e149-9937-47b1-8b8a-b7832842d181",
  "type": "TIMER",
  "action": "START"
}

### Get all achievements
GET http://localhost:8080/api/achievements

### Create a new achievement

### Get all achievements for a user
GET http://localhost:8080/api/achievements/d34096fe-420f-4d71-9b17-b5ec84490e20