package com.alessandra_alessandro.ketchapp.controllers;

import com.alessandra_alessandro.ketchapp.kafka.KafkaProducer;
import com.alessandra_alessandro.ketchapp.models.dto.PlanBuilderRequestDto;
import com.alessandra_alessandro.ketchapp.models.dto.PlanBuilderResponseDto;
import com.alessandra_alessandro.ketchapp.models.dto.TomatoDto;
import com.alessandra_alessandro.ketchapp.models.entity.TomatoEntity;
import com.alessandra_alessandro.ketchapp.models.entity.UserEntity;
import com.alessandra_alessandro.ketchapp.repositories.TomatoesRepository;
import com.alessandra_alessandro.ketchapp.repositories.UsersRepository;
import com.alessandra_alessandro.ketchapp.utils.EntityMapper;
import com.alessandra_alessandro.ketchapp.utils.GeminiApi;
import com.fasterxml.jackson.core.JsonProcessingException;
import jakarta.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

@Service
public class PlanBuilderControllers {

    private static final Logger log = LoggerFactory.getLogger(
        PlanBuilderControllers.class
    );
    private final TomatoesRepository tomatoesRepository;
    private final UsersRepository usersRepository;
    private final GeminiApi geminiApi;
    private final EntityMapper entityMapper;
    private final KafkaProducer kafkaProducer;

    @Autowired
    public PlanBuilderControllers(
        TomatoesRepository tomatoesRepository,
        UsersRepository usersRepository,
        GeminiApi geminiApi,
        EntityMapper entityMapper,
        KafkaProducer kafkaProducer
    ) {
        this.tomatoesRepository = tomatoesRepository;
        this.usersRepository = usersRepository;
        this.geminiApi = geminiApi;
        this.entityMapper = entityMapper;
        this.kafkaProducer = kafkaProducer;
    }

    /**
     * Creates a new study plan using the provided response DTO.
     * Saves tomato data to the database, sends an email notification to the user,
     * and returns the response generated by the Gemini API.
     *
     * @param dto DTO containing information for plan creation
     * @return ResponseEntity with the generated request DTO or error in case of failure
     * @throws JsonProcessingException
     */
    public ResponseEntity<PlanBuilderRequestDto> createPlanBuilder(
        PlanBuilderResponseDto dto
    ) {
        log.info("Received PlanBuilderResponseDto: {}", dto);
        PlanBuilderRequestDto geminiResponse = geminiApi.ask(dto);
        log.info("Gemini API response: {}", geminiResponse);
        if (geminiResponse == null) {
            log.info("Gemini response is null, returning bad request");
            return ResponseEntity.badRequest().build();
        }

        saveTomatoesFromGeminiResponse(dto, geminiResponse);
        String userEmail = resolveUserEmail(dto.getUserId());
        kafkaProducer.sendToKafka(userEmail, geminiResponse);
        return ResponseEntity.ok(geminiResponse);
    }

    /**
     * Saves the tomato entities extracted from the Gemini API response to the database.
     *
     * @param dto            The DTO containing user information.
     * @param geminiResponse The response DTO from the Gemini API.
     */
    private void saveTomatoesFromGeminiResponse(
        PlanBuilderResponseDto dto,
        PlanBuilderRequestDto geminiResponse
    ) {
        if (geminiResponse.getSubjects() == null) return;
        for (var subject : geminiResponse.getSubjects()) {
            log.info("Processing subject: {}", subject.getName());
            var tomatoes = subject.getTomatoes();
            if (tomatoes == null) continue;
            TomatoEntity prevTomato = null;
            for (PlanBuilderRequestDto.Tomato tomato : tomatoes) {
                log.info("Processing tomato: {}", tomato);
                var tomatoDto = TomatoDto.fromPlanBuilderTomato(
                    tomato,
                    dto.getUserId(),
                    subject.getName(),
                    prevTomato != null ? prevTomato.getId() : null
                );
                TomatoEntity tomatoEntity = entityMapper.tomatoDtoToEntity(
                    tomatoDto
                );
                log.info("Saving TomatoEntity: {}", tomatoEntity);
                TomatoEntity savedTomato = tomatoesRepository.save(
                    tomatoEntity
                );
                if (prevTomato != null) {
                    prevTomato.setNextTomatoId(savedTomato.getId());
                    log.info(
                        "Updating prevTomato with nextTomatoId: {}",
                        savedTomato.getId()
                    );
                    tomatoesRepository.save(prevTomato);
                }
                prevTomato = savedTomato;
            }
        }
    }

    /**
     * Resolves the user's email address from the user UUID.
     */
    private String resolveUserEmail(java.util.UUID userUUID) {
        String userEmail = usersRepository
            .findById(userUUID)
            .map(UserEntity::getEmail)
            .orElse("");
        log.info("User email resolved: {}", userEmail);
        return userEmail;
    }

    private String getCurrentJwtToken() {
        // Retrieve the JWT from the current HTTP request header
        try {
            ServletRequestAttributes attr =
                (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
            if (attr == null) return null;
            HttpServletRequest request = attr.getRequest();
            String authHeader = request.getHeader("Authorization");
            if (authHeader != null && authHeader.startsWith("Bearer ")) {
                return authHeader.substring(7);
            }
            return null;
        } catch (Exception e) {
            log.error("Could not extract JWT from HTTP request", e);
            return null;
        }
    }
}
